---
title: "DSlecture19"
author: "Hening CUi"
date: "11/18/2021"
output: github_document
---

```{r,echo = FALSE}
library (tidyverse)
library(viridis)
library(modelr)
library(mgcv)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

knitr::opts_chunk$set(
  fig.width = 8,
  fig.height =6,
  out.width = "90%"
)

options(
  ggplot2.continuous.color = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_color_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## Simulate a dataset

```{r}
set.seed(1)

nonlin_df = 
  tibble(
    id = 1:100,
    x = runif(100, 0, 1),
    y = 1 - 10 * (x - .3) ^ 2 + rnorm(100, 0, .3)
  )

nonlin_df %>% 
  ggplot(aes(x = x, y = y)) +
  geom_point()
```

Create spilts and plot and fit

```{r}
train_df = sample_n(nonlin_df, 80)

test_df = anti_join(nonlin_df, train_df)

ggplot(train_df, aes(x, y)) +
  geom_point() +
  geom_point(data = test_df, color = "red")
```

fit model

```{r}
linear_mod = lm(y ~ x, data = train_df)
smooth_mod = mgcv::gam(y ~ s(x), data = train_df)
wiggly_mod = mgcv::gam(y ~ s(x, k = 30), sp = 10e-6, data = train_df )
```

plot result

```{r}
train_df %>% 
  add_predictions(smooth_mod) %>% 
  ggplot(aes(x, y)) +
  geom_point() +
  geom_line(aes(y = pred))
```

```{r}
train_df %>% 
  add_predictions(wiggly_mod) %>% 
  ggplot(aes(x, y)) +
  geom_point() +
  geom_line(aes(y = pred)) #more complex
```


```{r}
train_df %>% 
  gather_predictions(linear_mod, smooth_mod, wiggly_mod) %>% 
  mutate(model = fct_inorder(model)) %>% 
  ggplot(aes(x = x, y = y)) + 
  geom_point() + 
  geom_line(aes(y = pred), color = "red") + 
  facet_wrap(~model)
```

quatify result

```{r}
rmse(linear_mod, test_df)
rmse(smooth_mod, test_df)
rmse(wiggly_mod, test_df)
```

## CV iteratively

use modelr::crossv_cv

```{r}
cv_df =
  crossv_mc(nonlin_df, 100) # sampling 100 times

cv_df %>% pull(train) %>% .[[1]] %>% as.tibble()
```

```{r}
cv_df = 
  cv_df %>% 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble)
  )
```

lets fit some models

```{r}
cv_df =
  cv_df %>% 
  mutate(
    linear_mod = map(.x = train, ~lm(y ~ x, data = .x)),
    smooth_mod = map(.x = train, ~gam(y ~ s(x), data = .x)),
    wiggly_mod = map(.x = train, ~gam(y ~ s(x, k = 30), sp = 10e-6, data = .x))
  ) %>% 
  mutate(
    rmselinear = map2_dbl(.x = linear_mod,.y = test, ~rmse(model = .x, data = .y)),
    rmsesmooth = map2_dbl(.x = smooth_mod,.y = test, ~rmse(model = .x, data = .y)),
    rmsewiggly = map2_dbl(.x = wiggly_mod,.y = test, ~rmse(model = .x, data = .y))
  )

```

look at output

```{r}
cv_df %>% 
  select(starts_with("rmse")) %>% 
  pivot_longer(
    rmselinear:rmsewiggly,
    names_to = "model",
    values_to = "rmse", 
    names_prefix = "rmse"
  ) %>% 
  ggplot(aes(x = model, y = rmse)) +
  geom_boxplot()
```
## child growth

```{r}
child_df = read_csv("nepalese_children.csv") %>% 
  mutate(weight_cp = (weight >7) * (weight-7))
```

```{r}
child_df %>% 
  ggplot(aes(x = weight, y = armc)) +
  geom_point(alpha = .2)
```

consider candidate model

```{r}
linear_mod = lm(armc ~ weight, data = child_df)
smooth_mod = gam(armc ~ s(weight), data = child_df)
pwl_mod = gam(armc ~ weight + weight_cp, data = child_df)
```

```{r}
child_df %>% 
  add_predictions(pwl_mod) %>% 
  ggplot(aes(weight, armc)) +
  geom_point(alpha =.2) + 
  geom_line(aes(y = pred), color = "red")
```

USe CV

```{r}
cv_df = 
  crossv_mc(child_df, 100)%>% 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble)
  )
```

```{r}
cv_df =
  cv_df %>% 
  mutate(
    linear_mod = map(.x = train, ~lm(armc ~ weight, data = .x)),
    smooth_mod = map(.x = train, ~gam(armc ~ s(weight), data = .x)),
    pwl_mod = map(.x = train, ~gam(armc ~ weight + weight_cp, data = .x))
  ) %>% 
  mutate(
    rmselinear = map2_dbl(.x = linear_mod,.y = test, ~rmse(model = .x, data = .y)),
    rmsesmooth = map2_dbl(.x = smooth_mod,.y = test, ~rmse(model = .x, data = .y)),
    rmsepwl = map2_dbl(.x = pwl_mod,.y = test, ~rmse(model = .x, data = .y))
  )

```

```{r}
cv_df %>% 
  select(starts_with("rmse")) %>% 
  pivot_longer(
    rmselinear:rmsepwl,
    names_to = "model",
    values_to = "rmse", 
    names_prefix = "rmse"
  ) %>% 
  ggplot(aes(x = model, y = rmse)) +
  geom_boxplot()
```